### ISSUE TITLE
Choose License

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#1]
We have to choose a license for this code:

I have three options in mind:
1- MIT License. While it allows for commercial usage, it is also not bad to have it. If any commercial developer might need to improve it or add extra functionality, they will do so and improve the library. It is also the default for scikit-learn. Since we base so much in sklearn, it might be a good idea to use this license and prevent any problem.

2- GPL V3 License. Does not allow our code to be packaged commercially. However, it does allow to modify it and use it to provide a service, commercially, without distributing the new code.

3- AGPL fixes the previous issue.

**Comment by fraimondo** [comment]
@kaurao We need to fix this ASAP. Currently there is no license and the project is public.

**Comment by kaurao** [comment]
Let's go with AGPL unless there is no clear reason not to.
