### ISSUE TITLE
[ENH] (Repeated)StratifiedKFold for Regression

### ISSUE THREAD

**Issue by Shammi270787** [juaml/julearn#106]
Create train and test splits deterministically based on the number of repeats so that
1. Each repeat has train/test samples from all the bins (e.g., age-groups) 
2. All the samples are included in the test set once so that we get predictions for all the samples.

**Comment by samihamdan** [comment]
Can you elaborate a bit more what you mean? 
For me it sounds like you just want to have KFold CV stratified by a variable which is not the target. 
In this specific case the variable would be an encoding of the age as a bins.
Is that correct?

**Comment by Shammi270787** [comment]
I mean to have a function that would perform stratified K-fold for the regression task.
