### ISSUE TITLE
[BUG] Julearn not working with sklearn 0.24

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#108]
@samihamdan can you develop what happens?

On a bigger topic, we need to handle dependencies better. The discussion started here: #107.

The biggest problem we have is sklearn or pandas changing in subsequent releases and creating a compatibility issue between julearn latest and sklearn/pandas latest at some point, until we fix julearn.

So we either keep specific versions as requirements, which for me is too strict.

If we fix specific versions, then we do not allow different versions of julearn with other's of scikit-learn. If we are flexible, then we might have this inconsistency. 

A possible solution would be to allow for future releases until majors. So for example, julearn 0.3.0 might require `0.25 > sklearn >= 0.22`. Given that 0.25 is not yet released. However, if then 0.25 is released, and it works with julearn 0.3.0, we will then have to release 0.3.1 with the updated requirements `0.26 > sklearn >= 0.22`. If it does not work, we will need to update julearn, but setting requirements `0.26 > sklearn >= 0.25`.

What do you think about this?

**Comment by samihamdan** [comment]
For the specific sklearn release of 0.24 I assigned myself and will work on it asap.

About the general issue: 
I like the idea of keeping an upper & lower boundary (for major releases) of required dependencies.
If I understand you correctly this is what you propose and I would agree that this is the best solution to keep julearn from breaking while being as flexible as possible.
