### ISSUE TITLE
[ENH] Model comparison interface

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#112]
Add a way to compare multiple models/pipelines in one call using cross validation.
One way would be to have a model comparison object on which you can use method `add_model` and later use method `run_comparison` (or similar function).

**Comment by fraimondo** [comment]
This is a feature I personally would like to have. We need to discuss this further how we want to do it. Can we have an example on how we want this API to be?

**Comment by fraimondo** [comment]
We have a stats module that now allows to directly compare model.

This issue also entails a higher-level API in which a _list_ of models is defined, and all of them automatically compared.

For the moment, we will close this issue, until we are sure that this higher-level functionality is really required.
