### ISSUE TITLE
[ENH] create_pipeline function

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#114]
A couple of issues (e.g. #112 #113 ) are based on the idea of using a julearn model/pipeline in other function then the `run_cross_validation`. In some situations I would even like to use a model in a custom/manual cv loop. 

For these situations it will be helpful to have a public function which uses the same inputs as `run_cross_validation`, but returns only a not trained pipeline which can be used however the user wants.

**Comment by fraimondo** [comment]
Was this issue addressed in #115?
