### ISSUE TITLE
[ENH] Make cv default similar to scikit-learn one

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#121]
We have observed a situation where a user set `cv=RepeatedKFold()` in `run_cross_validation`.
The user was not aware that this will apply to both inner and outer loops by default. 
This lead together with other things to a drastically increased computation time.

In the docstrings we note this behavior only in the inner cv option (in `model_params`  the `cv` argument).
This means if a user sets `cv` in `run_cross_validation` they will not be aware that they also use the same in the inner loop.

We should consider to note this in the  `run_cross_validation` `cv` argument or change the default behavior to be independent of each other. What do you think  @kaurao  @fraimondo

**Comment by fraimondo** [comment]
You insisted on this.

My vote was to not use any default and just rely on scikit-learn's defaults, which is cv=5.

So now the default is `cv = 'repeat:5_nfolds:5’` for `run_cross_validation` and to use the same one for the inner.

**Comment by samihamdan** [comment]
Ok, did not remember this was my idea. 
Then I would say my mind has changed and we will change it back to scikit-learn behavior.

**Comment by fraimondo** [comment]
Indeed my argument behind not using any repeated CV is because at the first try, users would like to see how the pipeline behaves and how's the output, but as a kind of test. Once that the code is ready to go, they might want to do repeated CV.

Adding 5 x 5 CV as default in both steps makes it a bit long to process to have a preliminary result.

**Comment by samihamdan** [comment]
Sure, I will change this issue to deal with both cv options. 
Initially, this was only about both cv being equal.
But we can change both cv options to default scikit-learn behavior in one PR
