### ISSUE TITLE
[BUG] Bug in the transformer wrapper implementation

### ISSUE THREAD

**Issue by Shammi270787** [juaml/julearn#122]
Can't access PCA attributes explained_variance/ n_components using
model.best_estimator_['pca'].explained_variance_

![image](https://user-images.githubusercontent.com/23641510/107970395-591e8900-6fb1-11eb-9cb5-db7db4da25a1.png)

**Comment by samihamdan** [comment]
To me this seems to be easy to fix by adapting the `__getitem__` in `meta.py`.

**Comment by fraimondo** [comment]
So if the item has a wrapper, bypass the wrapper?

Do we have a use case in which we don’t want this behaviour?

**Comment by samihamdan** [comment]
I actually wrote smth wrong above of course not the `__getitem__` . 
I wanted to make the trained attributes also attributes of the wrapper.


About your idea: 
So, you want that the `__getitem__` of the `ExtendedDataFramePipeline` bypasses the wrapper and returns the transformer itself ? 
If so I am a bit skeptical that this might not lead to some problems when people want to use the transformer for smth else and it behaves differently. 
If I misunderstood you please elaborate.

**Comment by fraimondo** [comment]
Now it makes more sense.

So the wrapper should inherit the attributes of the wrapped object.

Can we implement that?

**Comment by samihamdan** [comment]
Yes, sry I just swapped the 2 concepts in my mind for a second. 

So, what I would do is just assigning all attributes with a tailing `_` and all the parameter you can get with `get_params`  from the transformer to the wrapper. Something like this: 

0. use `dir(transformer)` to get a list of all attributes of the wrapped transformer.
1. Loop through attributes. Filter to keep  tailing `_` or in get_params().keys() 
2. Now we set the attribute and value to the wrapper. 

The wrapper has only  `apply_to` and `return_features` attributes itself. 
Those I would never overwrite. Maybe we should prevent transformers with these parameters at intit ?

**Comment by samihamdan** [comment]
We tried the above mentioned and other options to make the wrapper get the attrs of the wrapped transformer. All of these were either hard to maintain in the future, slow or had other downsides. 
Instead we decided to make the `ExtendedDataFramePipeline` get the wrapped transformer itself instead of the wrapper.
