### ISSUE TITLE
leave-k-families-out cross validation (to use eg. in twin-samples)

### ISSUE THREAD

**Issue by NevenaK** [juaml/julearn#123]
Hi there, thank you for the great toolbox!

I came across this paper from Poldrack et al. 2019 (Establishment of Best Practices for Evidence for Prediction; https://jamanetwork.com/journals/jamapsychiatry/article-abstract/2756204). Here he suggests "For example, in the presence of family structure, such as the sample used in the Human Connectome Project, a researcher might cross-validate across families (ie, leave-k-families-out) rather than individuals to address the nonindependence potentially induced by family structure." What do you think about that and is there a way to do that with julearn?

**Comment by fraimondo** [comment]
Hi!

The concept you are looking for is named _groups_. Is already part of scikit-learn and julearn.

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GroupKFold.html#sklearn.model_selection.GroupKFold

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeaveOneGroupOut.html#sklearn.model_selection.LeaveOneGroupOut

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeavePGroupsOut.html


You will need to call the `run_cross_validation` function specifying the CV strategy to use and which is the _groups_ column:

Check here: https://juaml.github.io/julearn/main/api.html#module-julearn.api

example:

```Python
from sklearn.model_selection import LeavePGroupsOut

cv = LeavePGroupsOut(n_groups=2)  # Leaves 2 groups for the test set

run_cross_validation(..., cv=cv, groups='family')
```

**Comment by NevenaK** [comment]
Thank you!
