### ISSUE TITLE
[ENH] Usage of Categorical Features

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#125]
What we want is that users can define features as being categorical features.
These features should then be ignored by a couple of transformers (or by transformers in general) unless specified differently. 
This is needed as you don't want to for example zscore categorical variables.
One easy way would be that we work with pandas Categorical column type. 
If a user defines variables to be categorical in pandas then we will treat them as categorical features in the pipeline.

**Comment by fraimondo** [comment]
@samihamdan: just to be sure, you are working with @verakye on this one, no?

**Comment by verakye** [comment]
Yes. I have a functioning version of it with some adaptations in api.py to give the user the possibility to define/pass categorical features. However, the usage of this version when someone ONLY has categorical features is functional but not very clear to the user what the default behaviour would be/how to best use it.

**Comment by fraimondo** [comment]
this is implemented in the new API: #183
