### ISSUE TITLE
[ENH] reference samples for preprocessing

### ISSUE THREAD

**Issue by kaurao** [juaml/julearn#143]
**Is your feature request related to a problem? Please describe.**
In many cases, e.g. clinical applications, a part of the data should be considered as normative/reference, e.g. healthy controls, and only this subset should be used for estimating preprocessing parameters, e.g. Z-scoring mean/std and PCA matrices.

**Describe the solution you'd like**
An argument to provide a data subset either as indices of samples or as a class label to be considered as the reference.

**Describe alternatives you've considered**
None

**Do you have a sample code that implements this outside of julearn?**
No

**Additional context**
None

**Comment by fraimondo** [comment]
I still do not understand much how this will interact with CV.

So the idea is to use a subset of the samples to compute PCA/Z-Score and then apply to the whole dataset? How is this implemented with a CV scheme?

Do we have a clear use case?

**Comment by fraimondo** [comment]
Implemented in #220
