### ISSUE TITLE
API Change surrounding inner cv

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#146]
I find the api for defining the inner cv no intuitive and would like to change it. 

## Current API (complete example later):
```python
model_params = model_params=dict(
    svm__C = [1,2,3],
    cv = StratifiedKFold(3),
    search='grid',
    search_params = dict(verbose=1)
)
```
## My Problem
As you can see we specify arguments of the `search` inside of `search_params`.  
But the argument `cv` is set outside of `seach_params` in `model_params`.  
This can and did lead to confusion for users, as `cv` is a param of `search`, 
 but if you set it inside of `search_params` it there will neither result in the correct output nor a warning or error.  

### Example of the Problem:
![image](https://user-images.githubusercontent.com/44375312/134226890-29bf6269-de9c-4be2-8417-024faf1837fb.png)

## Reproducible example of current API 

```python3 
import seaborn as sns 
from sklearn.model_selection import StratifiedKFold

from julearn import run_cross_validation
from julearn.utils import configure_logging
configure_logging(level='INFO')

df_iris = (sns.load_dataset('iris')
           .iloc[:100,:])
X = df_iris.columns[:-1].tolist()
y = 'species'

df_iris = sns.load_dataset('iris')
df_iris = df_iris.iloc[:100,:]

model_params = model_params=dict(
    svm__C = [1,2,3],
    cv = StratifiedKFold(3),
    search='grid',
    search_params = dict(verbose=1)
)
run_cross_validation(
    X=X , y=y, data=df_iris,
    model='svm', cv=3, 
    model_params=model_params
)
```

can be adjusted to also show the above mentioned strange behavior by changing `model_params`:
```python3
model_params = model_params=dict(
    svm__C = [1,2,3],
    search='grid',
    search_params = dict(
        cv = StratifiedKFold(3), verbose=1
    )
```

## Proposed Changes:
I would propose that we only allow setting inner cv as `cv` in `search_params`.

**Comment by fraimondo** [comment]
+1


Maybe do it as part of #145 ?
