### ISSUE TITLE
[ENH] Rename Estimator

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#158]
**Is your feature request related to a problem?
We call the folder for models estimator, but transformers are also estimators. 

**Describe the solution you'd like**
Therefore, I would like to rename it to models

**Describe alternatives you've considered**
Tutorials etc have to be adjusted to reference it correctly

**Comment by fraimondo** [comment]
I think we should support _both_ by adding a deprecation warning in next major release (0.3.0) that this will be removed in 0.3.2.

**Comment by samihamdan** [comment]
This was done in #183
