### ISSUE TITLE
Typos in Docs

### ISSUE THREAD

**Issue by LeSasse** [juaml/julearn#166]
I just went through documentation and these typos caught my eye (On https://juaml.github.io/julearn/main/pipeline.html)

Under "Model & Problem Type", it says:  
1. "In machine learning their are different problems you want to handle." This should be "In machine learning there are different problems you want to handle."
2. "You shout set problem_type to one of these 3 problem typed. By default, julearn uses the binary_classification type." This should read "You should set problem_type to one of these 3 problem typed. By default, julearn uses the binary_classification type."

Under "Preprocessing / concepts" it further says:
1. "By default users do not have to specify how to preprocess their data. In this case, julearn automatically standardizes the continuous features, the confounds and removes existing confound from the continuous features." I think in this case you want "confound" to be plural, so "confounds"?
2. "By default features will will not be preprocessed and confound removed in case a confound was specified." --> will is written twice

Under "Example":
1. "Assume we want not preprocess the confounds, zscore the transformer and then use a pca on the features before removing the confound from these features." should be "Assume we don't want to preprocess the confounds, ... ", also "zscore the transformer " should also probably say "zscore the features"

Under "Caveats ExtendedDataFramePipeline"
1. "This means that any any function which uses sklearn scorer functions instead of calling .score()" Any is written twice.

**Comment by samihamdan** [comment]
Thank you for your feedback. We have this included in the new documentation that will be merged to main.

**Comment by LeSasse** [comment]
> Thank you for your feedback. We have this included in the new documentation that will be merged to main.

No problem, you are welcome!
