### ISSUE TITLE
transform_target ExtendedDataFramePipeline

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#17]
I think there is some potential of refactoring `ExtendedDataFramePipeline`.
One of these is the following method:
```
    def transform_target(self, X, y):
        if self.y_transformer is not None:
            y_true = self.y_transformer.transform(X, y)
        else:
            y_true = y
        return y_true
```

Here, we only transform the target given some `X`.
Now in practice this `X` is always the `X_conf_trans`. 
My question is now: 
Should `transform_target` also do the `transform_confounds`.
This would simplify multiple calls of the function e.g. in scoring. 

On the other hand, I think that being able to only transform the target easily with any `X` as input might helps  to investigate a given model . In theory ppl. can always use `.y_transformer.transform` to transform the target given any `X` without changing the confounds before.

What do you think @fraimondo  ?

**Comment by fraimondo** [comment]
The idea of the pipeline is that it applies all the transforms in order, while the user does not have to worry about it.

In this case, the transformation steps are:
1- confounds
2- target
3- features

if we allow for target transformations (confounds, targets), then it should be the same as calling `transform`. It should apply whatever transformation is applied on the pipeline.

Let's say a user wants to implement a different CV strategy manually.
```Python
for train, test in mycv.split(X, y):
    model.fit(X[train], y[train])
    y_true = model.transform_target(X[test], y[test])
    y_pred = model.predict(X[test])
    score(y_true, y_pred)
```

I still have not go through the `ExtendedDataFramePipeline`, but I do believe that most of the current methods should be private:
* `recode_columns`
* `set_column_mappers`
* `convert_column_name`

**Comment by samihamdan** [comment]
Ok sounds good. I will adjust it accordingly. 
Maybe, I will keep one private way of just transforming the target without changing the confounds.
Might be important for debugging, testing etc.
