### ISSUE TITLE
[ENH] harmonization as a preprocessing step 

### ISSUE THREAD

**Issue by kaurao** [juaml/julearn#172]
**Is your feature request related to a problem? Please describe.**
It will be useful to have harmonization as a preprocessing step.

**Describe the solution you'd like**
 Add a transformer based on the method implemented in neuroHarmonize for tabular data. User must provide a "site" variable. 

**Describe alternatives you've considered**
Doing it outside julearn but then implementing other steps and nested CV is a pain.

**Do you have a sample code that implements this outside of julearn?**
Nope 

**Additional context**
Nope

**Comment by fraimondo** [comment]
Doesn't this rely on JuHarmonize being finished?
