### ISSUE TITLE
[BUG] ValueError: All elements must be matched.

### ISSUE THREAD

**Issue by giuseppe-amendola** [juaml/julearn#176]
**Describe the bug**
I keep receiving this error message: ValueError: All elements must be matched. The following are missing: ['PropertyGFABuilding(s)', 'SiteEnergyUse(kBtu)', 'TotalGHGEmissions', 'Hospital (General Medical & Surgical)', 'Repair Services (Vehicle, Shoe, Locksmith, etc)', 'Personal Services (Health/Beauty, Dry Cleaning, etc)', 'bins']

I am trying to perform Stratified K-fold CV for regression problem, using dataframe but it seems not working. 

Here's my code

import math
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold

from julearn import run_cross_validation
from julearn.model_selection import StratifiedGroupsKFold

# combining features and target together in one dataframe
data_df = pd.concat([X, y_consommation], axis=1)
y="y_consommation"
x=data.columns.tolist()

#Define number of splits for CV and create bins/group for stratification

num_splits = 7

num_bins = math.floor(len(data) / num_splits)  # num of bins to be created
bins_on = y_consommation  # variable to be used for stratification
qc = pd.cut(bins_on.tolist(), num_bins)  # divides data in bins
data['bins'] = qc.codes
groups = 'bins'

#Train a linear regression model with stratification on target

cv_stratified = StratifiedGroupsKFold(n_splits=num_splits, shuffle=False)
scores_strat, model = run_cross_validation(X=x, y=y,data=data_df, cv=cv_stratified, problem_type='regression', model='linreg', return_estimator='final', scoring='neg_mean_absolute_error')

RETURNING THIS ERROR:

ValueError: All elements must be matched. The following are missing: ['PropertyGFABuilding(s)', 'SiteEnergyUse(kBtu)', 'TotalGHGEmissions', 'Hospital (General Medical & Surgical)', 'Repair Services (Vehicle, Shoe, Locksmith, etc)', 'Personal Services (Health/Beauty, Dry Cleaning, etc)', 'bins']

**Comment by fraimondo** [comment]
Hi!

It seems that you have a mismatch between the X and data_df (or something is not correct there).

Can you run your script but first setting the logging level to info?

``` Python
from julearn.utils import configure_logging
configure_logging(level='INFO')

**Comment by fraimondo** [comment]
Also keep in mind this:

```
data_df = pd.concat([X, y_consommation], axis=1)
y="y_consommation"
x=data.columns.tolist()
```

You are setting `x = data.columns.tolist()` but `data_df` is created from `X`, not from `data`.

**Comment by samihamdan** [comment]
Due to no follow after a couple of months I will close this issue. If your question is not resolved please reopen this issue.
