### ISSUE TITLE
Restrict input data types.

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#21]
As it is right now, if `df` is not None, we expect X, y and confounds to be columns in the data frame. This also allows for #19 and #20 to be implemented.

However, the problem arises when there's no `df`. We allow weird combinations between numpy arrays and pandas objects. And later on the processing, we start creating data frames from this objects. This will create issues when combining the data frames, particularly if they have repeated column names or indexes. And my particular concern is about the kind of errors the user will receive. They will be very deep pandas indexing errors.

I propose that when `df` is None, all the other elements must be numpy arrays.

If a user does not now know to combine a few data frames into one, we can create an example.

**Comment by kaurao** [comment]
I agree with you for requiring numpy arrays.
The reason to allow users to specify a file instead of a `df` is to reduce
the amount of code a user needs to write to interface with `julearn`.

**Comment by fraimondo** [comment]
Issue #20 was something I had in mind. #19 is a great addition that I did not think of. 

The discussion here is how to avoid mistakes by restricting a bit what happens when you don't specify the `df` parameter. 

Unless @samihamdan has any comment on this (he's the one using confounds), I will restrict what happens when `df=None`.

**Comment by samihamdan** [comment]
Yes. Please restrict what people are able to input. 
Please make sure that the resulting DataFrame has strings as column names. 
Then we can just provide `create_pipeline` the confounds and categorical_features as a list of the assigned column names.
