### ISSUE TITLE
[DOC]: Stacking models "apply_to"

### ISSUE THREAD

**Issue by antogeo** [juaml/julearn#259]
### Which element of the documentation do you want to modify and why?

Hello ppl, 
I need your help for the stacking model.

Copying from the documentation of the stacking models 

```
model_1 = PipelineCreator(problem_type="regression", apply_to="type1")
model_1.add("filter_columns", apply_to="*", keep="type1")
model_1.add("svm", kernel="linear", C=np.geomspace(1e-2, 1e2, 10))

```

Does the second _apply_to_ cancel the first one? 
Also, what is the the _keep_ parameter doing? It s not clear to me from the output message

> `
Out: ...2024-04-04 14:46:47,506 - julearn - INFO - Setting hyperparameter keep = type1`

**Comment by LeSasse** [comment]
`model_1 = PipelineCreator(problem_type="regression", apply_to="type1") `

This sets the apply_to parameter as to "type1" as a default and therefore all steps that don't explicitly set a `apply_to` parameter. See the documenation for the PipelineCreator here: https://juaml.github.io/julearn/main/api/generated/julearn.PipelineCreator.html#julearn-pipelinecreator

`model_1.add("filter_columns", apply_to="*", keep="type1")`

This means in this step the input columns are filtered. `keep` is the parameter that specifies which columns to keep. `apply_to=*` means that the step filters "type1" from all (`*`) features. See the Documentation for filter columns: https://juaml.github.io/julearn/main/api/generated/julearn.transformers.FilterColumns.html#julearn.transformers.FilterColumns

`model_1.add("svm", kernel="linear", C=np.geomspace(1e-2, 1e2, 10))`

That means it applies the step of fitting a model on the default `apply_to` features i.e. `"type1"`.

So what is happening is that it is keeping type1 features and then fitting a model on it, which is what the documentation sasys:

> Let’s first configure a [PipelineCreator](https://juaml.github.io/julearn/main/api/generated/julearn.PipelineCreator.html#julearn.PipelineCreator) to fit an SVR on the features of "type1"`

**Comment by antogeo** [comment]
I see! thanks a lot @LeSasse
