### ISSUE TITLE
[ENH] example-wise confounds

### ISSUE THREAD

**Issue by kaurao** [juaml/julearn#26]
possibility to specify confounds to be regress out from each example. This is useful in specific cases where we want to control for subject-specific information. This is quite a niche application so **low priority**.

There are several possibilities:
- confounds as a separate `df` 
- a list of lists defining feature-confounds relationship

**Comment by fraimondo** [comment]
Just a quick comment.

1. Confounds as a separate `df`:
The idea is to avoid having 2 data frames. With numpy arrays, the user has to make sure that the rows match. But with dataframes, we might have index issues when joining them. So as in #21 , all the variables are strings and df is a data frame, or all variables are numpy arrays. We will provide an example on how to merge data frames and check. 

2. How is this interpreted?

**Comment by fraimondo** [comment]
I still do not grasp the idea behind this feature. @kaurao: can you clarify?

**Comment by fraimondo** [comment]
closed due to inaction
