### ISSUE TITLE
Document pipeline

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#39]
The section on pipeline in the documentation needs work.

Our extended pipeline deviates from the one in scikit-learn, in the sense that from the API we specify preprocess X, y and confounds.

Questions to answer:

- How are this elements combined in the pipeline?
- What are the valid things to do?
- What are the restrictions?
- What will the API allow us to do but we should not do?

**Comment by fraimondo** [comment]
The file to edit is [docs/pipeline.rst](https://github.com/juaml/julearn/blob/main/docs/pipeline.rst)

**Comment by samihamdan** [comment]
The basic documentation is done. 
This will be an ongoing task while some of the components of the pipeline change. 
Still, I would say that the initial aim for this issue and milestone is fulfilled.

**Comment by samihamdan** [comment]
There are some things that have to be adjusted before milestone 2. 
Therefore, I reopened it.
E.g. Problems of users working with returned estimator. 
Understanding that it includes all steps etc.

**Comment by fraimondo** [comment]
When I opened this issue, I though of having two kinds of documentations. One external, facing the user, and one internal, facing the developers.

This is a good start: https://juaml.github.io/julearn/pipeline.html

However, I would:

- Change it's title to "Understanding the pipeline"
- Start with a gentle introduction on how this pipeline applies the confounds, X, y prerprocessing and the classification/regression. (Via the main API function)
- Continue with how this could be extended (tweaked)
- Finalise with an advanced section, explaining the column type system and maybe the internals.
- Put all the function references in the `api.rst` file.
