### ISSUE TITLE
[ENH] Set GridSearchCV scoring parameter.

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#4]
This is how we currently do grid search:
```Python
 if len(hyper_params) > 0:
     pipeline = GridSearchCV(pipeline, hyper_params, cv=cv_inner)
```

An important element is the scoring function to determine what is a better hyper parameter, that is, the `scoring` parameter
of the GridSearchCV object.

As it is right now, the number of parameters in the `run_cross_validation` function is growing.

I suggest we put all the model selection parameters into one single parameter `model_selection` which will be a dictionary.

so this:
```Python
def run_cross_validation(
        X, y, model,
        data=None,
        confounds=None,
        problem_type='binary_classification',
        preprocess_X=['z_score'],
        preprocess_y=None,
        preprocess_confounds=['z_score'],
        hyperparameters=None,
        output_estimator=False, print_result=True,
        cv_evaluation='repeat:5_nfolds:5',
        cv_model_selection='same',
        model_selection_scoring='roc_auc',
        scoring=None,
        pos_labels=None,
        seed=None)
```
Can be something like this:

```Python
def run_cross_validation(
        X, y, model,
        data=None,
        confounds=None,
        problem_type='binary_classification',
        preprocess_X=['z_score'],
        preprocess_y=None,
        preprocess_confounds=['z_score'],
        output_estimator=False, print_result=True,
        cv='repeat:5_nfolds:5',
        model_selection=None,
        scoring=None,
        pos_labels=None,
        seed=None)
```

And we can set up model selection like this:
```Python
model_selection = {
    'cv': '5',
    'hyperparameters': {'svm__C': [0.001, 0.01, 0.1, 1, 10, 100]},
    'scoring': 'roc_auc'
}
```

What do you think?

This will also be compatible with future enhancements:
* Change the model selection strategy (instead of `GridSearchCV`)'
* Allow to set up other model selection parameters.
* Allow to use several scorers for evaluation (call `cross_validate` instead of `cross_val_score`) while keeping the same scoring for model selection.

**Comment by samihamdan** [comment]
Yes I agree. 
I was also thinking about using a dict to reduce the arguments for `run_cross_validation`.

I only see one disadvantage: no hinting for the arguments or autocomplete. 
Don't know whether this is important, but this would bother me as a user for sure.
In case this important we could additionally add a function in which we have proper docstring 
=> autocomplete etc. for those who want.
So ppl. could either just write the dict themselves or basically do the same with a function which outputs there input as a dict. 

One question: 
Don't you want to include the outer cv option in the dict as well ? 
I mean it makes sense if called `model_selection` to not include model evaluation arguments. 
But I don't know whether such a distinction makes sense for all the users.

For compatibility I agree.
I would also like to move to `cross_validate` asap.

**Comment by samihamdan** [comment]
I can start working on this and also see whether we can already add `cross_validate`.
