### ISSUE TITLE
[ENH] Confounds edge cases

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#40]
There are some more things we have not implemented or thought about considering confounds. 

0. Confound removal of the target is planned and easy to implement.
I did not do it yet, but will include it soon. 
What do you @fraimondo  think, should I add it to `confounds.py`, because it is a confound removal operation.
Or should I add it to `target.py` because it is a wrapper around confounds for the targets.  

Now to the important part of this issue
1. Present confounds, but no removal.
Currently, the confound removal operation removes the confounds from the possible feature space. 
Therefore, when there is no confound removal the confounds will be used by the predictive model at the end. 
I would like to remove the confounds if they are still present before using the predictive model. 
Does anyone see a problem with this? 

2. Confounds as features: 
We discussed that possibility to add confounds as features even when there is confound removal. 
Programmatically, this is no problem.
Conceptually, I would like to discuss when to add the confounds as features and which 
transformations should be applied to them. 
* We could add the confounds at the beginning as normal features.
Problem: what transformations should be applied to them. At least confound removal might not make sense. 
* We could add an option to the confound removal operation, which adds the confound as a feature after confound removal. 
This would mean the new features (former confounds) would have only be transformed as the confounds before removal. 
Afterwards, they would be treated like any other feature. 
    - Here, we might run into following problem: 
We don't know whether the added features (former confounds) are continuous or categorical features. 
Maybe, we would need to add multiple column_type options for this feature. Or we could just distinguish between 
categorical and  continuous confounds. This information might even make sense for some confound removal operations, 
which we have not yet considered. 

Do you see other ways how we should handle these cases? 
Do you know other edge cases? 
What are your thoughts on these options? 
@fraimondo  @kaurao

**Comment by fraimondo** [comment]
0. I would add it to confounds. If `confounds.py` becomes too large, then you can make it a directory and place several .py files in it, one for features, other for target.

1. I don't get why this is the case. If the user specifies `confounds=`, then they must be removed from `X`. But after the removal, all the rest of the steps of the pipeline should work only on `X`, and not `confounds.

2. This should be the case when there is overlapping between `X` and `confounds`: 
Example:
```
X = ['a', 'b', 'c']
confounds = ['c']
```
I guess the behaviour here would be to remove the confound C from A and B, and then continue working with A-C, B-C and C.

**Comment by samihamdan** [comment]
1: Maybe, my knowledge of the user api is outdated. 
But from what I can see is, that you can provide confounds but not do confound removal. 
This is what I meant.

2. This was the question. In theory there are other use cases or options. 
Then I would make it a parameter of confound removal instead. 
When set_to `confound_as_feature = True` we would return a variable with the column_name of the confound, but another column_type.
