### ISSUE TITLE
[ENH] Cleanup passthrough transformers

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#42]
Currently `PassThroughTransformer` and `TargetPassThroughTransformer` are not used any more. 

They were the default confounds and y preprocessing steps, but they were replaced by `if`. I don't see any reason why we need this wrappers that do nothing.

Current uses:
* PassThroughTransformer:
  - Listed as an available transformer.
  - In `test_dataframe` to test for the `DataFrameTransformer`

* TargetPassThroughTransformer:
  - Only to be listed as an available transformer.

If it's only needed for testing purposes, then it can be added as a local class in the `test_dataframe.py`. If needed for more than one test file, it can be added to `utils.testing.py`.

**Comment by samihamdan** [comment]
I think it would be fine to put it into testing
