### ISSUE TITLE
[ENH] Preprocessors Convenience Class

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#57]
We use `steps` similar to sklearn to create our pipelines. 
I think it is good to keep it that way, nut remembering which step argument is at which position is kind of bothersome.
I think the solution would be a preprocessor convenience class. 
Basically, all it does is provide a better api to create these steps. 
The output would be the same list of tuples as we use as inputs until now, but it would provide sane defaults 
and good keyword arguments. Also it should integrate seamlessly with `get_transformer`

My suggestion looks a bit like this pseudo code: 

```
class preprocessor:
   def __init__(self, confouding_pipe=False):
     ....
   def add_step(name, transformer, returned_features, transformed_columns):
     ....
   def add_available_step(name, transformed_columns):
     # gets steps by name from available transformers
     ....
   def compile(self):
     returns list_of_tuples
```

Users could use it like this: 
```
preprocess_features = (preprocessor()
                             .add_step('zscore', StandardScaler(),...)
                             .add_available_step('remove_confound', 'all')
                       ).compile()
```

**Comment by fraimondo** [comment]
I do not get why is it bothersome. The current api has three parameters, named `preprocess_X`, `preprocess_y` and `preprocess_confounds`. The order in which these steps are applied was agreed that it will remain static. So first confounds and target, and then X. 

If the user is the one specifying these parameter, there's no way the user can't "remember" the order.

BTW: the order in which these steps are applied should be in the documentation.

I personally find an overkill to have to do all these steps just to do a zscore and remove confounds.

**Comment by samihamdan** [comment]
Sry, I think I should have clarified this a bit more. 
I do not mean the typical case in the user facing api and I don't want to touch the order of  `preprocess_X`, ` preprocess_y` and `preprocess_confounds`

What I mean is how to provide the list of tuples to  each of these arguments inside of  functions like `create_dataframe_pipeline`, `create_extended_pipeline` etc. 
So, this effects more whats going on in the background or in case users want to go beyond the defaults. 


E.g. from the example of advanced_confound_removal:

```
    preprocess_steps_features=[
        ('remove_confound', DataFrameConfoundRemover(
            keep_confounds=True), 'subset', 'all'),
        ('change_column_types', ChangeColumnTypes('.*confound', 'continuous'),
         'from_transformer', 'all'),
        ('pca', *get_transformer('pca'))
    ],
 ```

Here, I find it bothersome to write out all 4 steps in the correct order inside of each tuple. 
What I propose would mean that you don't have to look up what step was in which order because you could just use: 

```
preprocess_steps_features = (preprocessor()
    .add_step(transformer=ChangeColumnTypes(...),  return_features='from_transformer')
).compile()

```

This means you could define them in any order and you get immediate access to the docstring. 
You do not have to specify all, if you only want to change the last one. 
You don't have to remember what indx meant what.
The advantage for cases with available transformers is that we do not run into the strange syntax, 
which you can see above.  Using tuple unpacking does not make it more readable.

**Comment by samihamdan** [comment]
I will close this issue, because it is aimed at making the non user facing things better for the user and this is currently not in scope
