### ISSUE TITLE
[ENH] Setting Hyperparameters in ExtendedDataFramePipeline

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#58]
It would be nice to set the hyperparameters like we access them.
So, that `extended_pipe[step]` uses the same step as `extended_pipe.set_params(step__param=val)`.

**Comment by fraimondo** [comment]
What is the current behaviour. I thought it was the exact same.

**Comment by fraimondo** [comment]
@samihamdan Any update on this? is this still relevant for 0.3.0?

**Comment by samihamdan** [comment]
We are able to set hyperparams in #183 using the PipelineCreator in a way that resolves this.
