### ISSUE TITLE
[ENH] Provide a way of obtaining fold-wise predictions and not just scores.

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#69]
Sometimes, users might want to get the actual predictions based on the cross-validation, instead of the scores.

This can be done by using a *special* value as scorer `predict`, which instead of calling `cross_validate`, calls `cross_val_predict`.

**Comment by fraimondo** [comment]
This feature has been requested. However, we need to check how the CV scheme will behave in cases where one sample is part of several test folds.

**Comment by samihamdan** [comment]
We implemented this to get cv predictions through the inspect module.
