### ISSUE TITLE
[ENH] Function to preprocess X and y for analysis purposes

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#7]
I am preparing an example in which I want to plot the decision plane on an SVM, using a bivariate example.

I figured out that in order to do it, I will need to be able to preprocess X and use that data for the plot.

And finally, for researching and debugging, it might also be interesting to see what is the classifier being trained on. In other words, let's say we remove confounds, z-score, PCA and then use a classifier. What are all these transformations doing to my data?

In scikit-learn, you can achieve that by adding a 'passthrough' element as the last step of the pipeline. In our case, I think it will be better to modify the `ExtendedDataFramePipeline` and include that functionality there.

My take would be to add an extra function called `preprocess` in which both X and y are transformed, and the last step of the pipeline is not applied. And to avoid doing the last step of the pipeline, I would temporary remove it:

```Python
    def preprocess(self, X, y):
        if self.y_transformer is not None:
            y_trans = self.y_transformer.fit_transform(X, y)
        else:
            y_trans = y

        old_model = self.dataframe_pipeline.steps.pop()
        X_trans = self.transform(X)
        self.dataframe_pipeline.steps.append(old_model)
        return X_trans, y_trans
```

The documentation of preprocess will state that it runs every step but the last one. So if someone tries to use it with a custom pipeline, they will know that the last step won't be applied.

@samihamdan what do you think of this solution?

**Comment by samihamdan** [comment]
Agreed, I was struggling how to provide such an interface. 
Just make sure to not forget the confound `confound_dataframe_pipeline`. 
This pipe is there to change the confound before transforming the target. 
This is important when confound removing the target with a transformed confound. 

 
I just see that there is actually a bug that the fit method is not using the transformed confound for the target. 
I will open a quick issue.
