### ISSUE TITLE
[ENH] Modified t-test for CV

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#75]
Add a `stats` module with the possibility of running the modified t-test for CV: https://medium.com/analytics-vidhya/using-the-corrected-paired-students-t-test-for-comparing-the-performance-of-machine-learning-dc6529eaa97f

**Comment by fraimondo** [comment]
I won't make it for v0.2.0. It will be for next release.

**Comment by samihamdan** [comment]
This is added by #183
