### ISSUE TITLE
Repeated Stratified Kfolds for regression analysis

### ISSUE THREAD

**Issue by Shammi270787** [juaml/julearn#79]
Maybe I missing some concepts here, so please correct me if I am wrong. So, this is what I tried this:

# Using diabetes data from regression example:

# Divide target in 5 bins (categories) for stratified k-fold
qc = pd.cut(data_diabetes['target'].tolist(), bins=5, precision=1) 

# use these bins to create splits
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=200).split(data_diabetes, qc.codes)

scores, model = run_cross_validation(X=X, y=y, data=data_diabetes, cv=cv, problem_type='regression', model='ridge', return_estimator='final', scoring='neg_mean_absolute_error')

scores_df = pd.DataFrame(scores)

When I display the scores, the repeat number is always 0.
What am I missing here?

<img width="1440" alt="Screenshot 2020-11-27 at 16 23 01" src="https://user-images.githubusercontent.com/23641510/100463936-f235b600-30cc-11eb-8b7e-dfc9df5af08c.png">

**Comment by Shammi270787** [comment]
Ah, I think I got it. It is because I used the 'split' method.

**Comment by fraimondo** [comment]
Exactly. You only need to initialise it.
