### ISSUE TITLE
[ENH] Target Transformers

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#9]
Currently, we allow one target transformer. 
People can wrap complete normal pipelines in as target transformer, but I think we will need a custom `TargetTrafransorfmerPipeline` for situations where we want use multiple custom target transformer using both X and y etc.

Furthermore, we have no compatibility with `sklearn.compose.TransformedTargetRegressor`. 
Our aim was it to provide a way to change the ground truth used for scoring, but I think we should also allow for inverse transforming. This would also allow for the same use cases handled by  `sklearn.compose.TransformedTargetRegressor`.

**Comment by samihamdan** [comment]
Also, because of its special situation the hyperparameters might be a bit off. 
This has to be solved as well.

**Comment by fraimondo** [comment]
@samihamdan Will this issue still be valid for 0.3.0?

**Comment by fraimondo** [comment]
implemented in #183
